#!/usr/bin/env bash
#
# Interactive setup wizard for the HoundDog.ai self-hosted stack. Generates the .env file
# consumed by compose.yaml. Press Enter at any prompt to accept the default shown in brackets.

set -euo pipefail

cd "$(dirname "$0")"

say() { printf '%s\n' "$*"; }
fail() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

command -v docker > /dev/null 2>&1 \
    || fail "Docker is required but was not found. Install it first: https://docs.docker.com/get-docker/"
docker compose version > /dev/null 2>&1 \
    || fail "Docker Compose v2 is required but was not found. Update Docker or install the compose plugin."

if [ -f .env ]; then
    say "A .env file already exists in $(pwd)."
    read -r -p "Overwrite it? Existing settings will be lost. [y/N] " answer
    case "$answer" in
        [Yy]*) ;;
        *)
            say "Keeping the existing .env; nothing to do."
            exit 0
            ;;
    esac
fi

generate_secret() {
    # $1 = number of random bytes; prints them base64-encoded without padding or newlines.
    if command -v openssl > /dev/null 2>&1; then
        openssl rand -base64 "$1" | tr -d '\n='
    else
        head -c "$1" /dev/urandom | base64 | tr -d '\n='
    fi
}

say ""
say "HoundDog.ai self-hosted setup"
say "============================="
say ""
say "Generating a secret key (encrypts sensitive data at rest) ..."
secret_key="$(generate_secret 48)"
say "Done. It will be written to .env; keep a copy somewhere safe, because encrypted"
say "settings are unrecoverable without it."

say ""
say "Database:"
say "  1) Bundled Postgres managed by this compose stack (default)"
say "  2) External Postgres that you provide"
while :; do
    read -r -p "Choose 1 or 2 [1]: " db_choice
    db_choice="${db_choice:-1}"
    case "$db_choice" in
        1 | 2) break ;;
        *) say "Please enter 1 or 2." ;;
    esac
done

postgres_url=""
postgres_password=""
if [ "$db_choice" = "1" ]; then
    postgres_password="$(generate_secret 24)"
    say "Generated a random password for the bundled Postgres."
else
    say ""
    say "Enter the connection URL of your Postgres server, in the form:"
    say "  postgres://USER:PASSWORD@HOST:PORT/DATABASE"
    say "Leave it empty to enter host, port, database, user, and password separately."
    while :; do
        read -r -p "Postgres URL []: " postgres_url
        if [ -z "$postgres_url" ]; then
            read -r -p "Host [localhost]: " db_host
            db_host="${db_host:-localhost}"
            while :; do
                read -r -p "Port [5432]: " db_port
                db_port="${db_port:-5432}"
                case "$db_port" in
                    '' | *[!0-9]*) say "The port must be a number (e.g. 5432)." ;;
                    *) break ;;
                esac
            done
            read -r -p "Database [hounddog]: " db_name
            db_name="${db_name:-hounddog}"
            read -r -p "User [hounddog]: " db_user
            db_user="${db_user:-hounddog}"
            read -r -s -p "Password (input hidden): " db_password
            say ""
            [ -n "$db_password" ] || {
                say "A password is required for the external database."
                continue
            }
            postgres_url="postgres://${db_user}:${db_password}@${db_host}:${db_port}/${db_name}"
            break
        fi
        case "$postgres_url" in
            postgres://* | postgresql://*) break ;;
            *) say "The URL must start with postgres:// or postgresql://." ;;
        esac
    done
fi

umask 077
{
    printf '# Generated by setup.sh. Keep this file private: it contains secrets.\n\n'
    printf 'HOUNDDOG_SECRET_KEY=%s\n\n' "$secret_key"
    if [ "$db_choice" = "1" ]; then
        printf 'COMPOSE_PROFILES=postgres\n'
        printf 'HOUNDDOG_POSTGRES_PASSWORD=%s\n' "$postgres_password"
    else
        printf 'HOUNDDOG_POSTGRES_URL=%s\n' "$postgres_url"
    fi
} > .env

say ""
say "Wrote $(pwd)/.env (owner-only permissions)."
say ""
say "Next steps:"
say "  1. Run ./start.sh"
say "  2. Open http://localhost:3300 and create your organization and admin account."
say "     Do this right away: until the first account exists, anyone who can reach the"
say "     instance can claim it."
